version: "3.7"

services:
  app:
    image: learning-docker/motel-api-node-mongo:v1
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu thay đổi code thì bên trong sẽ tự động cập nhật
    environment: # params định nghĩa trong file .env
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      # - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: /app/entrypoint.sh # Có thêm dòng này
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
